service:
  role: loan
spring:
  liquibase:
    enabled: false
  application.name: lending-system
  profiles:
    active: async # Standard für normale Entwicklung - alternativ kann Profil 'kafka' genutzt werden
  datasource:
    # lokales Starten in der IDE mit URL, im Container ohne URL
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lending}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate.ddl-auto: create # dev: update | create-drop | create
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      #hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
      #hibernate.transaction.coordinator_class: jdbc

  idempotence4j:
    retention:
      enabled: true
      period: P30D # Bewahre Keys für 30 Tage auf (ISO-8601 Format)
      purge:
        schedule: "0 0 2 * * ?" # Täglich um 2 Uhr morgens aufräumen
      batchSize: 100


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false  # Wichtig für Transaktionen!
      properties:
        isolation.level: read_committed
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true

management.endpoints.web.exposure.include: "health,info,metrics"
logging.level.org.springframework.kafka: INFO
logging.level.de.demo.lending: DEBUG
#logging.level.org.hibernate.engine.transaction.jta: DEBUG
#logging.level.org.hibernate: DEBUG

# Outbox (global, von common/outbox genutzt)
outbox:
  enabled: false
  publisher:
    enabled: false
  table: outbox
  publish-interval-ms: 500
  batch-size: 100