server.port: 8081
service.role: loan
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/loans
  kafka:
    consumer.group-id: loan-service
  liquibase:
    change-log: classpath:/db/changelog/loan/master.yaml
  jpa:
    hibernate:
      ddl-auto: none


outbox:
  enabled: true
  publisher:
    enabled: true
