server.port: 8082
service.role: inventory
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/inventory
  kafka:
    consumer.group-id: inventory-service
  liquibase:
    change-log: classpath:/db/changelog/inventory/inventory-changelog.yaml
  jpa:
    hibernate:
      ddl-auto: none

outbox:
  enabled: true
  publisher:
    enabled: true‚