server.port: 8082
service.role: inventory
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/inventory
  kafka:
    consumer.group-id: inventory-service

outbox:
  enabled: true
  publisher:
    enabled: false‚