spring:
  application.name: order-flow
  datasource:
    #url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orders}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      properties:
        isolation.level: read_committed
    producer:
      acks: all
      retries: 5
      properties:
        enable.idempotence: true

management.endpoints.web.exposure.include: "health,info,metrics"
logging.level.org.springframework.kafka: INFO
logging.level.de.example.orderflow: DEBUG

# Outbox (global, von common/outbox genutzt)
outbox:
  table: outbox
  publish-interval-ms: 500
  batch-size: 100