databaseChangeLog:

  # Inventory-Tabellen
  - changeSet:
      id: inventory-001
      author: you
      changes:
        - createTable:
            tableName: inventory_copy
            columns:
              - column:
                  name: id
                  type: UUID
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: book_id
                  type: UUID
                  constraints:
                    nullable: false
              - column:
                  name: state
                  type: VARCHAR(32)
                  constraints:
                    nullable: false
              - column:
                  name: location
                  type: VARCHAR(64)
              - column:
                  name: updated_at
                  type: TIMESTAMPTZ
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: TIMESTAMPTZ
                  constraints:
                    nullable: false

        - createIndex:
            tableName: inventory_copy
            indexName: idx_inventory_book
            columns:
              - column:
                  name: book_id